name: proxymama_app
description: "ProxyMama Android & iOS Client App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase SDKs
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.3
  google_sign_in: ^6.1.6

  # State Management & Helpers
  provider: ^6.1.1
  qr_flutter: ^4.1.0
  intl: ^0.19.0
  google_fonts: ^6.1.0
  flutter_spinkit: ^5.2.0
  share_plus: ^7.2.1
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
